# Generated by Django 5.2 on 2025-04-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Стаття як покращити себе ', 'verbose_name_plural': 'Статті як покращити себе'},
        ),
        migrations.AlterField(
            model_name='article',
            name='main_page',
            field=models.BooleanField(default=True, help_text='Показувати на головній сторінці ', verbose_name='Головна'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.article', verbose_name='Стаття як покрашити себе'),
        ),
    ]
